FROM gcr.io/google_containers/etcd-amd64:3.1.12
FROM gcr.io/google_containers/kube-apiserver-amd64:v1.10.3
FROM gcr.io/google_containers/kube-controller-manager-amd64:v1.10.3
FROM gcr.io/google_containers/kube-scheduler-amd64:v1.10.3
MAINTAINER Anthony <wy18300@163.com>
